Ruben.Books.Web/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Antlr.Runtime;
using Ruben.Books.DataLayer;
using Ruben.Books.Domain;
using Ruben.Books.Repository;
using Ruben.Books.Web.Models;
using WebGrease.Css.Extensions;

namespace Ruben.Books.Web.Controllers
{
    public class BooksController : Controller
    {
        private IBooksRepository _repo;
        private IUnitOfWork<BooksContext> _unitOfWork;
        private ICategoryRepository _categoryRepository;
        private IBookBadgeRepository _badgeRepo;
        private IAuthorRepository _authorRepo;

        public BooksController(IUnitOfWork<BooksContext> unitOfWork, 
            IBooksRepository repo, 
            ICategoryRepository categoryRepository, 
            IBookBadgeRepository badgeRepo,
            IAuthorRepository authorRepo)
        {
            _categoryRepository = categoryRepository;
            _unitOfWork = unitOfWork;
            _repo = repo;
            _badgeRepo = badgeRepo;
            _authorRepo = authorRepo;
        }

        //
        // GET: /Books/

        public ActionResult Index(BookFilterVM filter)
        {           
            ViewBag.Title = "All books";
            var viewModel = new BookAndFilterVM
            {
                Books = GetBooks(filter),
                Filter = filter
            };
            var categories = new List<Category>() { new Category {Name="_none", Id=-1}};
            categories.AddRange( _categoryRepository.All.ToList());
            viewModel.CategoryIds = new SelectList(categories, "Id", "Name", -1);

            return View(viewModel);
        }

        public ActionResult IndexContent(BookFilterVM filter)
        {               
            return View("BookVMIndex", GetBooks(filter));
        }

        private List<BookVM> GetBooks(BookFilterVM filter)
        {
            var booksQuery = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings);

            // TODO: convert to filter domain model and pass to repository
            if (filter != default(BookFilterVM))
            {
                if (filter.IsRead.HasValue)
                {
                    booksQuery = filter.IsRead.Value ?
                        booksQuery.Where(_ => _.Readings.Any()) :
                        booksQuery.Where(_ => !_.Readings.Any());
                }
                if (filter.CategoryId.HasValue && filter.CategoryId.Value > 0)
                {
                    booksQuery = booksQuery.Where(_ => _.CategoryId == filter.CategoryId.Value);
                }
            }   

            var books = booksQuery.OrderByDescending(_=>_.Id).ToList()
                .Select(_ => new BookVM(_));

            return (filter != null && filter.IsRead.HasValue && filter.IsRead.Value) ?
                books.OrderByDescending(_ => _.LastRead).ToList() :
                books.OrderByDescending(_ => _.Id).ToList();

        }

        //
        // GET: /Books/Details/5

        public ActionResult Details(int id)
        {
            var book = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings)
                .Single(_ => _.Id == id);

            return View(book);
        }

        //
        // GET: /Books/Create

        public ActionResult Create()
        {
            ViewData["Categories"] = new SelectList(_categoryRepository.All.ToList(), "Id", "Name", 1);
            return View(new CreateOrUpdateBookVM());
        }

        //
        // POST: /Books/Create

        [HttpPost]
        public ActionResult Create(CreateOrUpdateBookVM book)
        {
            if (this.ModelState.IsValid)
            {
                var bookToAdd = new Book()
                {
                    State = State.Added,
                    CategoryId = book.CategoryId,
                    FirstPublished = new DateTime(book.YearFirstPublished, 1, 1),
                    Published = new DateTime(book.YearPublished, 1, 1),
                    Isbn = book.Isbn,
                    Pages = book.Pages,
                    Tags = book.Tags,
                    Title = book.Title,
                    Authors = book.AuthorIds.Select(_ => new Author() { Id = _ }).ToList(),
                    Owned = book.Owned
                };

                _repo.InsertOrUpdateGraph(bookToAdd);
                _unitOfWork.Save();
               
                return RedirectToAction("Details", new { id = bookToAdd.Id });
            }

            ViewData["Categories"] = new SelectList(_categoryRepository.All.ToList(), "Id", "Name", 1);
            return View(book);
        }

        //
        // GET: /Books/Edit/5

        public ActionResult Edit(int id)
        {
            var book = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings)
                .Single(_ => _.Id == id);
            ViewData["Categories"] = new SelectList(_categoryRepository.All.ToList(), "Id", "Name", 1);
            return View(new CreateOrUpdateBookVM(book));
        }

        //
        // POST: /Books/Edit/5

        [HttpPost]
        public ActionResult Edit(CreateOrUpdateBookVM book)
        {
            if (this.ModelState.IsValid)
            {
                var bookToUpdate = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings)
                    .Single(_ => _.Id == book.Id);
                                
                bookToUpdate.State = State.Modified;
                bookToUpdate.CategoryId = book.CategoryId;
                bookToUpdate.FirstPublished = new DateTime(book.YearFirstPublished, 1, 1);
                bookToUpdate.Published = new DateTime(book.YearPublished, 1, 1);
                bookToUpdate.Isbn = book.Isbn;
                bookToUpdate.Pages = book.Pages;
                bookToUpdate.Tags = book.Tags;
                bookToUpdate.Title = book.Title;                
                bookToUpdate.Owned = book.Owned;

                bookToUpdate.Authors = _authorRepo.All.Where(_ => book.AuthorIds.Contains(_.Id)).ToList();
                
                _repo.InsertOrUpdate(bookToUpdate);
                _unitOfWork.Save();

                return RedirectToAction("Details", new { id = bookToUpdate.Id });
            }

            ViewData["Categories"] = new SelectList(_categoryRepository.All.ToList(), "Id", "Name", 1);
            return View(book);
        }

        //
        // GET: /Books/Delete/5

        public ActionResult Delete(int id)
        {
            var book = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings)
                .Single(_ => _.Id == id);

            return View(book);
        }

        //
        // POST: /Books/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _repo.Delete(id);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Ruben.Books.Web/Controllers/EarnedBadgesController.cs
using Ruben.Books.DataLayer;
using Ruben.Books.Repository;
using Ruben.Books.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ruben.Books.Web.Controllers
{
    public class EarnedBadgesController : Controller
    {
        private readonly IBookBadgeRepository _repo;
        private readonly IUnitOfWork<BooksContext> _unitOfWork;

        public EarnedBadgesController(IUnitOfWork<BooksContext> unitOfWork, IBookBadgeRepository repo)
        {
            _repo = repo;
            _unitOfWork = unitOfWork;
        }
        //
        // GET: /EarnedBadges/

        public ActionResult Index()
        {
            var badges = _repo.AllIncluding(_ => _.Reading.Book)
                .Where(_ => !_.IsSpent)
                .ToList();

            return View(badges.Select(_=>new BookBadgeVM
                {
                    EarnedDate = _.Reading.Date,
                    Book = _.Reading.Book.Title,
                    Id = _.Id,
                    BookId = _.Reading.Book.Id,
                }));
        }

        public ActionResult Spend(int id)
        {
            _repo.SpendBadge(id);            
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

    }
}

Ruben.Books.Web/Controllers/ReadingController.cs
using Ruben.Books.DataLayer;
using Ruben.Books.Domain;
using Ruben.Books.Repository;
using Ruben.Books.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Ruben.Books.Web.Controllers
{
    public class ReadingController : Controller
    {
        private IReadingsRepository _repo;
        private IBooksRepository _bookRepo;
        private IBookBadgeRepository _badgeRepo;
        private IUnitOfWork<BooksContext> _unitOfWork;

        public ReadingController(
            IUnitOfWork<BooksContext> unitOfWork,
            IReadingsRepository repo,  
            IBooksRepository bookRepo,
            IBookBadgeRepository badgeRepo)
        {
            _unitOfWork = unitOfWork;
            _repo = repo;
            _bookRepo = bookRepo;
            _badgeRepo = badgeRepo;
        }

        //
        // GET: /Books/

        public ActionResult Index()
        {
            // TODO: pass paging?
            var readings = _repo.GetTimeline();

            var viewModel = readings.Select(_ => new BookVM(_)).ToList();
            
            return View(viewModel);
        }

        public ActionResult MarkRead(int bookId)
        {
            var book = _bookRepo.Find(bookId);
            return View(new PrefillMarkReadVM() {
                BookId = bookId,
                Pages = book.Pages
            });
        }

        [HttpPost]
        public ActionResult MarkRead(Reading reading)
        {
            if(ModelState.IsValid)
            {
                var book = _bookRepo.Find(reading.BookId);
                reading.Book = book;
                _badgeRepo.CreateBadgesForBookRead(reading);
                reading.State = State.Added;
                _repo.InsertOrUpdateGraph(reading);
                _unitOfWork.Save();
                return Json(new {Success=true}, JsonRequestBehavior.AllowGet);
            }

            var errors = ModelState
                .Where(_ => _.Value.Errors.Any())
                .Select(_=>new {Field=_.Key, Error=_.Value.Errors.First().ErrorMessage})
                .ToList();
            
            //this.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
            return Json(new { Success=false,Errors = errors }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int id)
        {
            var reading = _repo.Find(id);
            _repo.Delete(id);
            _unitOfWork.Save();
            return RedirectToAction("Details", "Books", new { id=reading.BookId });
        }
    }
}

Ruben.Books.Web/Views/Shared/BookVMIndex.cshtml
@model IEnumerable<Ruben.Books.Web.Models.BookVM>
@{
    Layout = null;
}
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Published)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pages)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastRead)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Owned)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            <a href="@Url.Action("Details", "Books", new { id=item.Id})">
                @Html.DisplayFor(modelItem => item.Title)
            </a>
        </td>
        <td>            
            @Html.DisplayFor(modelItem => item.Published)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pages)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastRead)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Owned)
        </td>
       
    </tr>
}

</table>

Ruben.Books.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")

        <script src="/Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
        <script src="/Scripts/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/Scripts/jquery-ui/jquery.ui.autocomplete.min.js" type="text/javascript"></script>
        <link href="/Content/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" type="text/css" />
       
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="/Scripts/bootstrap/css/bootstrap.min.css">
        <!-- Optional theme -->
        <link rel="stylesheet" href="/Scripts/bootstrap/css/bootstrap-theme.min.css">
        <!-- Latest compiled and minified JavaScript -->
        <script src="/Scripts/bootstrap/js/bootstrap.min.js"></script>
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Reading")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("New book", "Create", "Books")</li>
                            <li>@Html.ActionLink("Books", "Index", "Books")</li>
                            <li>@Html.ActionLink("Timeline", "Index", "Reading")</li>
                            <li>@Html.ActionLink("Statistics", "Index", "Statistics")</li>
                            <li>@Html.ActionLink("Badges", "Index", "EarnedBadges")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @RenderSection("scripts", required: false)
    </body>
</html>