Ruben.Books.Web/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ruben.Books.Repository;
using Ruben.Books.Domain;
using Ruben.Books.DataLayer;

namespace Ruben.Books.Web.Controllers
{
    public class AuthorController : Controller
    {
        private IAuthorRepository _authorRepository;
        private IUnitOfWork<BooksContext> _unitOfWork;

        public AuthorController(IAuthorRepository authorRepository, IUnitOfWork<BooksContext> unitOfWork)
        {
            _authorRepository = authorRepository;
            _unitOfWork = unitOfWork;
        }

        //
        // GET: /Author/Find/x
        public JsonResult Get(int[] ids)
        {
            var authors = _authorRepository.All
                .Where(_ => ids.Contains(_.Id))
                .Select(_ => new { _.Id, _.Name });
            return Json(authors.ToList(), JsonRequestBehavior.AllowGet);

        }

        public JsonResult Find(string term)
        {
            var found = _authorRepository.FindAuthorByName(term);
            return Json(found.Select(_ => new {Id = _.Id, Name = _.Name}).ToList(),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult Create(string name)
        {
            var found = _authorRepository.FindAuthorByName(name);

            int authorId = 0;
            if (found.Count() == 0)
            {
                var author = new Author()
                {
                    State = State.Added,
                    Name = name
                };

                _authorRepository.InsertOrUpdate(author);
                _unitOfWork.Save();
                authorId = author.Id;
            }
            else
            {
                authorId = found.First().Id;
            }
            return Json(new { Id = authorId, Name = name }, JsonRequestBehavior.AllowGet);
        }

    }
}

Ruben.Books.Web/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Antlr.Runtime;
using Ruben.Books.DataLayer;
using Ruben.Books.Domain;
using Ruben.Books.Repository;
using Ruben.Books.Web.Models;
using WebGrease.Css.Extensions;

namespace Ruben.Books.Web.Controllers
{
    public class BooksController : Controller
    {
        private IBooksRepository _repo;
        private IUnitOfWork<BooksContext> _unitOfWork;
        private ICategoryRepository _categoryRepository;
        private IBookBadgeRepository _badgeRepo;
        private IAuthorRepository _authorRepo;

        public BooksController(IUnitOfWork<BooksContext> unitOfWork, 
            IBooksRepository repo, 
            ICategoryRepository categoryRepository, 
            IBookBadgeRepository badgeRepo,
            IAuthorRepository authorRepo)
        {
            _categoryRepository = categoryRepository;
            _unitOfWork = unitOfWork;
            _repo = repo;
            _badgeRepo = badgeRepo;
            _authorRepo = authorRepo;
        }

        //
        // GET: /Books/

        public ActionResult Index(BookFilterVM filter)
        {           
            ViewBag.Title = "All books";
            var viewModel = new BookAndFilterVM
            {
                Books = GetBooks(filter),
                Filter = filter
            };
            var categories = new List<Category>() { new Category {Name="_none", Id=-1}};
            categories.AddRange( _categoryRepository.All.ToList());
            viewModel.CategoryIds = new SelectList(categories, "Id", "Name", -1);

            return View(viewModel);
        }

        public ActionResult IndexContent(BookFilterVM filter)
        {               
            return View("BookVMIndex", GetBooks(filter));
        }

        private List<BookVM> GetBooks(BookFilterVM filter)
        {
            var booksQuery = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings);

            // TODO: convert to filter domain model and pass to repository
            if (filter != default(BookFilterVM))
            {
                if (filter.IsRead.HasValue)
                {
                    booksQuery = filter.IsRead.Value ?
                        booksQuery.Where(_ => _.Readings.Any()) :
                        booksQuery.Where(_ => !_.Readings.Any());
                }
                if (filter.CategoryId.HasValue && filter.CategoryId.Value > 0)
                {
                    booksQuery = booksQuery.Where(_ => _.CategoryId == filter.CategoryId.Value);
                }
            }   

            var books = booksQuery.OrderByDescending(_=>_.Id).ToList()
                .Select(_ => new BookVM(_));

            return (filter != null && filter.IsRead.HasValue && filter.IsRead.Value) ?
                books.OrderByDescending(_ => _.LastRead).ToList() :
                books.OrderByDescending(_ => _.Id).ToList();

        }

        //
        // GET: /Books/Details/5

        public ActionResult Details(int id)
        {
            var book = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings)
                .Single(_ => _.Id == id);

            return View(book);
        }

        //
        // GET: /Books/Create

        public ActionResult Create()
        {
            ViewData["Categories"] = new SelectList(_categoryRepository.All.ToList(), "Id", "Name", 1);
            return View(new CreateOrUpdateBookVM());
        }

        //
        // POST: /Books/Create

        [HttpPost]
        public ActionResult Create(CreateOrUpdateBookVM book)
        {
            if (this.ModelState.IsValid)
            {
                var bookToAdd = new Book()
                {
                    State = State.Added,
                    CategoryId = book.CategoryId,
                    FirstPublished = new DateTime(book.YearFirstPublished, 1, 1),
                    Published = new DateTime(book.YearPublished, 1, 1),
                    Isbn = book.Isbn,
                    Pages = book.Pages,
                    Tags = book.Tags,
                    Title = book.Title,
                    Authors = book.AuthorIds.Select(_ => new Author() { Id = _ }).ToList(),
                    Owned = book.Owned
                };

                _repo.InsertOrUpdateGraph(bookToAdd);
                _unitOfWork.Save();
               
                return RedirectToAction("Details", new { id = bookToAdd.Id });
            }

            ViewData["Categories"] = new SelectList(_categoryRepository.All.ToList(), "Id", "Name", 1);
            return View(book);
        }

        //
        // GET: /Books/Edit/5

        public ActionResult Edit(int id)
        {
            var book = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings)
                .Single(_ => _.Id == id);
            ViewData["Categories"] = new SelectList(_categoryRepository.All.ToList(), "Id", "Name", 1);
            return View(new CreateOrUpdateBookVM(book));
        }

        //
        // POST: /Books/Edit/5

        [HttpPost]
        public ActionResult Edit(CreateOrUpdateBookVM book)
        {
            if (this.ModelState.IsValid)
            {
                var bookToUpdate = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings)
                    .Single(_ => _.Id == book.Id);
                                
                bookToUpdate.State = State.Modified;
                bookToUpdate.CategoryId = book.CategoryId;
                bookToUpdate.FirstPublished = new DateTime(book.YearFirstPublished, 1, 1);
                bookToUpdate.Published = new DateTime(book.YearPublished, 1, 1);
                bookToUpdate.Isbn = book.Isbn;
                bookToUpdate.Pages = book.Pages;
                bookToUpdate.Tags = book.Tags;
                bookToUpdate.Title = book.Title;                
                bookToUpdate.Owned = book.Owned;

                bookToUpdate.Authors = _authorRepo.All.Where(_ => book.AuthorIds.Contains(_.Id)).ToList();
                
                _repo.InsertOrUpdate(bookToUpdate);
                _unitOfWork.Save();

                return RedirectToAction("Details", new { id = bookToUpdate.Id });
            }

            ViewData["Categories"] = new SelectList(_categoryRepository.All.ToList(), "Id", "Name", 1);
            return View(book);
        }

        //
        // GET: /Books/Delete/5

        public ActionResult Delete(int id)
        {
            var book = _repo.AllIncluding(_ => _.Category, _ => _.Authors, _ => _.Readings)
                .Single(_ => _.Id == id);

            return View(book);
        }

        //
        // POST: /Books/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _repo.Delete(id);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Ruben.Books.Web/Controllers/ReadingController.cs
using Ruben.Books.DataLayer;
using Ruben.Books.Domain;
using Ruben.Books.Repository;
using Ruben.Books.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Ruben.Books.Web.Controllers
{
    public class ReadingController : Controller
    {
        private IReadingsRepository _repo;
        private IBooksRepository _bookRepo;
        private IBookBadgeRepository _badgeRepo;
        private IUnitOfWork<BooksContext> _unitOfWork;

        public ReadingController(
            IUnitOfWork<BooksContext> unitOfWork,
            IReadingsRepository repo,  
            IBooksRepository bookRepo,
            IBookBadgeRepository badgeRepo)
        {
            _unitOfWork = unitOfWork;
            _repo = repo;
            _bookRepo = bookRepo;
            _badgeRepo = badgeRepo;
        }

        //
        // GET: /Books/

        public ActionResult Index()
        {
            // TODO: pass paging?
            var readings = _repo.GetTimeline();

            var viewModel = readings.Select(_ => new BookVM(_)).ToList();
            
            return View(viewModel);
        }

        public ActionResult MarkRead(int bookId)
        {
            var book = _bookRepo.Find(bookId);
            return View(new PrefillMarkReadVM() {
                BookId = bookId,
                Pages = book.Pages
            });
        }

        [HttpPost]
        public ActionResult MarkRead(Reading reading)
        {
            if(ModelState.IsValid)
            {
                var book = _bookRepo.Find(reading.BookId);
                reading.Book = book;
                _badgeRepo.CreateBadgesForBookRead(reading);
                reading.State = State.Added;
                _repo.InsertOrUpdateGraph(reading);
                _unitOfWork.Save();
                return Json(new {Success=true}, JsonRequestBehavior.AllowGet);
            }

            var errors = ModelState
                .Where(_ => _.Value.Errors.Any())
                .Select(_=>new {Field=_.Key, Error=_.Value.Errors.First().ErrorMessage})
                .ToList();
            
            //this.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
            return Json(new { Success=false,Errors = errors }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int id)
        {
            var reading = _repo.Find(id);
            _repo.Delete(id);
            _unitOfWork.Save();
            return RedirectToAction("Details", "Books", new { id=reading.BookId });
        }
    }
}

Ruben.Books.Web/Views/Books/Create.cshtml
@model Ruben.Books.Web.Models.CreateOrUpdateBookVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <script>
        $(document).ready(function () {

            $("#createAuthor").hide();
            $("#authorSearch").keyup(function () {
                if ($(this).val()) {
                    $("#createAuthor").show();
                }
                else {
                    $("#createAuthor").hide();
                }
            });

            $("#authorSearch").autocomplete({
                source: function (request, response) {
                    $.get("/Author/Find", { term: request.term }, function (data) {
                        response($.map(data, function (c) {
                            return {
                                label: c.Name,
                                id: c.Id
                            };
                        }));
                    });
                },
                select: function (event, ui) {
                    // TODO: create function for the following and reuse in click event below
                    $("#authors").append($('<option>', {
                        value: ui.item.id,
                        text: ui.item.label
                    }));
                    $('#authors option').prop('selected', 'selected');
                    $('#authorSearch').val('');
                    $("#createAuthor").hide();
                    event.preventDefault();
                }
            });

            $("#createAuthor").click(function () {

                $.get("/Author/Create", { name: $("#authorSearch").val() }, function (data) {
                    $("#authors").append($('<option>', {
                        value: data.Id,
                        text: data.Name
                    }));
                    $('#authors option').prop('selected', 'selected');
                    $('#authorSearch').val('');
                    $("#createAuthor").hide();
                });

            });

            $("#clearAuthors").click(function () {

                $("#authors").empty();

            });


            @if (Model.AuthorIds.Any())
            {
                <text>
                $.ajax({
                    url: '@Url.Action("Get", "Author")',
                    data: { ids: @Html.Raw(Json.Encode(Model.AuthorIds)) },
                    traditional: true,
                    success: function(result) {
                        $.each(result, function() {
                            $("#authors").append($('<option>', {
                                value: this.Id,
                                text: this.Name,
                                selected: true
                            }));
                        });
                    }
                });
                </text>
            }
        });
    </script>

    <fieldset>
        <legend>Book</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.AuthorIds)
        </div>
        <div class="editor-field">

            <input id="authorSearch" type="text" name="" /><a href="#" id="createAuthor">create author?</a>
            <br />
            <select id="authors" name="AuthorIds" multiple></select>
            @Html.ValidationMessageFor(model => model.AuthorIds)
            <br />
            <a id="clearAuthors" href="#">clear</a>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.YearFirstPublished)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.YearFirstPublished)
            @Html.ValidationMessageFor(model => model.YearFirstPublished)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.YearPublished)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.YearPublished)
            @Html.ValidationMessageFor(model => model.YearPublished)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Isbn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Isbn)
            @Html.ValidationMessageFor(model => model.Isbn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Pages)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Pages)
            @Html.ValidationMessageFor(model => model.Pages)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CategoryId, (SelectList)ViewData["Categories"])
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Owned)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Owned)
            @Html.ValidationMessageFor(model => model.Owned)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tags)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tags)
            @Html.ValidationMessageFor(model => model.Tags)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ruben.Books.Web/Views/Books/Delete.cshtml
@model Ruben.Books.Domain.Book

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Book</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstPublished)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstPublished)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Published)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Published)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Isbn)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Isbn)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Pages)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pages)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CategoryId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsRead)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsRead)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back", "Details", new { id=Model.Id})
    </p>
}

Ruben.Books.Web/Views/Books/Details.cshtml
@model Ruben.Books.Domain.Book

@{
    ViewBag.Title = "book details";
}

<h2>Details</h2>

<script>
    $(document).ready(function () {

        $("#markRead").click(function () {
            
            bookId = @Model.Id;            
            $.get("/Reading/MarkRead", { bookId: bookId }, function (data) {

                $("#bookCommand").html(data);         

            });
        });

    });
</script>
<fieldset>
    <legend>Book</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Authors)
    </div>
    <div class="display-field">
        @foreach (var author in Model.Authors)
        {
            <span>@author.Name</span>
        }
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.FirstPublished)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstPublished)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Published)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Published)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Isbn)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Isbn)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Pages)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pages)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Category)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.IsRead)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsRead)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Readings)
    </div>
    <div class="display-field">
        @foreach (var reading in Model.Readings)
        {
            <span>@reading.Date @Html.ActionLink("Delete", "Delete", "Reading", new {id=reading.Id}, null)</span>
        }
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id }) |
    <a href="#" id="markRead">Mark read</a>

</p>

<div id="bookCommand" />

Ruben.Books.Web/Views/Books/Edit.cshtml
@model Ruben.Books.Web.Models.CreateOrUpdateBookVM

@{
    ViewBag.Title = "Edit";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <script>
        $(document).ready(function () {

            $("#createAuthor").hide();
            $("#authorSearch").keyup(function () {
                if ($(this).val()) {
                    $("#createAuthor").show();
                }
                else {
                    $("#createAuthor").hide();
                }
            });

            $("#authorSearch").autocomplete({
                source: function (request, response) {
                    $.get("/Author/Find", { term: request.term }, function (data) {
                        response($.map(data, function (c) {
                            return {
                                label: c.Name,
                                id: c.Id
                            };
                        }));
                    });
                },
                select: function (event, ui) {
                    // TODO: create function for the following and reuse in click event below
                    $("#authors").append($('<option>', {
                        value: ui.item.id,
                        text: ui.item.label
                    }));
                    $('#authors option').prop('selected', 'selected');
                    $('#authorSearch').val('');
                    $("#createAuthor").hide();
                    event.preventDefault();
                }
            });

            $("#createAuthor").click(function () {

                $.get("/Author/Create", { name: $("#authorSearch").val() }, function (data) {
                    $("#authors").append($('<option>', {
                        value: data.Id,
                        text: data.Name
                    }));
                    $('#authors option').prop('selected', 'selected');
                    $('#authorSearch').val('');
                    $("#createAuthor").hide();
                });

            });

            $("#clearAuthors").click(function () {

                $("#authors").empty();

            });


            @if (Model.AuthorIds.Any())
            {
                <text>
                $.ajax({
                    url: '@Url.Action("Get", "Author")',
                    data: { ids: @Html.Raw(Json.Encode(Model.AuthorIds)) },
                    traditional: true,
                    success: function(result) {
                        $.each(result, function() {
                            $("#authors").append($('<option>', {
                                value: this.Id,
                                text: this.Name,
                                selected: true
                            }));
                        });
                    }
                });
                </text>
            }
        });
    </script>

    <fieldset>
        <legend>Book</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.AuthorIds)
        </div>
        <div class="editor-field">

            <input id="authorSearch" type="text" name="" /><a href="#" id="createAuthor">create author?</a>
            <br />
            <select id="authors" name="AuthorIds" multiple></select>
            @Html.ValidationMessageFor(model => model.AuthorIds)
            <br />
            <a id="clearAuthors" href="#">clear</a>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.YearFirstPublished)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.YearFirstPublished)
            @Html.ValidationMessageFor(model => model.YearFirstPublished)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.YearPublished)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.YearPublished)
            @Html.ValidationMessageFor(model => model.YearPublished)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Isbn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Isbn)
            @Html.ValidationMessageFor(model => model.Isbn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Pages)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Pages)
            @Html.ValidationMessageFor(model => model.Pages)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CategoryId, (SelectList)ViewData["Categories"])
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Owned)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Owned)
            @Html.ValidationMessageFor(model => model.Owned)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tags)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tags)
            @Html.ValidationMessageFor(model => model.Tags)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to book", "Details", "Books", new { id = @Model.Id }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ruben.Books.Web/Views/Books/Index.cshtml
@model Ruben.Books.Web.Models.BookAndFilterVM



<h2>@ViewBag.Title</h2>

<script>
    $(document).ready(function () {
        
        $("#filter_read").val(@Model.Filter.IsRead.ToString().ToLower());
        $("#filter_category").change(function () {
            $.get("/Books/IndexContent/", { IsRead: $("#filter_read").is(':checked'), CategoryId: $("#filter_category").val() }, function (data) {

                $("#booksContainer").html(data);

            });
        });
        $("#filter_read").change(function () {
            $.get("/Books/IndexContent/", { IsRead: this.checked, CategoryId: $("#filter_category").val() }, function (data) {

                $("#booksContainer").html(data);

            });
        });
    });    
</script>
<div class="bookFilters">
    filters    
    <div>is read: <input id="filter_read" type="checkbox" /></div>
    <div>category: @Html.DropDownList("filter_category", Model.CategoryIds)</div>
</div>

<div id="booksContainer">
    
    @Html.Partial("BookVMIndex", Model.Books)
</div>